feat(machines): Add notification to show number of selected machines MAASENG-1355
canonical/maas-ui pull request #4964
Opened 2023-06-05 09:23 UTC by ndv99

## Done

- Added a notification to show the number of machines currently selected
- Created MachineListSelectedCount component
- Exported `getCurrentPageDisplayedMachineCount` function from `MachineListDisplayCount` to assist with [MAASENG-1688](https://warthogs.atlassian.net/browse/MAASENG-1688)

## QA

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Go to machine list
- Select a few machines
- Ensure a notification is displayed with the correct number of machines selected
- Click "Select all X machines"
- Ensure all machines are selected
- Click "Clear selection"
- Ensure selection is cleared
- Enter a filter into the searchbox and repeat the above steps, ensuring that "filtered" is correctly shown in the notificaiton

## Fixes

Fixes [MAASENG-1355](https://warthogs.atlassian.net/browse/MAASENG-1355)

## Screenshots

### Some selected

![image](https://github.com/canonical/maas-ui/assets/35104482/0839c413-4693-4107-9d6b-0da6d5fc5cf5)

### All selected

![image](https://github.com/canonical/maas-ui/assets/35104482/48c22f5b-9290-4a66-aa74-db62b0d2f2be)

### Filtered selected

![image](https://github.com/canonical/maas-ui/assets/35104482/58d33102-1508-4d08-bdd3-f86ea8963e2a)

### All filtered selected

![image](https://github.com/canonical/maas-ui/assets/35104482/8b53d399-7ec1-4d3c-825b-76784565852e)

2023-06-05 09:23 UTC, webteam-app commented
Demo starting at https://maas-ui-4964.demos.haus

2023-06-05 13:54 UTC, petermakowski requested changes
Columns are no longer aligned correctly (I suspect the `expanded` prop to be the culprit), see the screenshot below

<img width="1546" alt="Google Chrome screenshot 000210@2x" src="https://github.com/canonical/maas-ui/assets/7452681/a124383f-0040-408f-b280-a7085363054e">

2023-06-06 10:19 UTC, ndv99 commented on src/app/machines/views/MachineList/_index.scss
> +  // }
I just pushed a commit removing that :wink:

2023-06-06 10:20 UTC, ndv99 commented on src/app/machines/views/MachineList/_index.scss
> +  // }
wait no i didnt i forgot to save

2023-06-06 10:20 UTC, petermakowski commented on src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
> +  const renderRows = useMemo(
```suggestion
  const machineRows = useMemo(
```
`render` implies it's a render function

2023-06-06 10:20 UTC, petermakowski commented on src/app/machines/views/MachineList/MachineListTable/MachineListTable.tsx
> +        rows={machinesLoading ? skeletonRows : renderRows}
```suggestion
        rows={machinesLoading ? skeletonRows : machineRows}
```

2023-06-06 10:26 UTC, petermakowski approved these changes

2023-06-06 10:47 UTC, merged