Maaseng 1173 allow soft stop power mode
canonical/maas-ui pull request #5139
Opened 2023-09-04 11:20 UTC by Jay-Topher

## Done

- Add soft stop power mode option to power cycle
- Add soft power off option for IPMI machines

## QA

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

- Visit `/MAAS/r/machines` and select one machine from the list of machines
- Click on "Power Cycle" and ensure there is a "Soft power off" option.
- Click on the "Soft power off" and ensure that a side panel shows up.
- Ensure that the side panel has an icon with a tooltip instruction.

- From the list of machines, find a machine with an IPMI power type that is powered on
- From the power column, click on the "Take action" menu and ensure you see the soft off option
- Ensure that the machine turns off  after clicking the "Soft off' option.

## Fixes

Fixes: #2675  .
[MAASENG-1173](https://warthogs.atlassian.net/browse/MAASENG-1173)

## Screenshots
![image](https://github.com/canonical/maas-ui/assets/47540149/18c06010-2ba6-40b2-8095-940daeccc97e)
![image](https://github.com/canonical/maas-ui/assets/47540149/7d6d5ef3-2589-4869-9fac-22266537d56a)

2023-09-04 11:20 UTC, webteam-app commented
Demo starting at https://maas-ui-5139.demos.haus

2023-09-04 12:59 UTC, ndv99 reviewed
Small change for a11y, but otherwise I think this is looking good

2023-09-04 12:59 UTC, ndv99 commented on src/app/base/components/InfoIconTooltip/InfoIconTooltip.tsx
> +    <Tooltip message={message} position="right">
Might be worth using the TooltipButton component here, so the tooltip stays visible if you click the icon

2023-09-04 13:45 UTC, petermakowski requested changes

2023-09-04 13:45 UTC, petermakowski commented on src/app/base/components/AppSidePanel/AppSidePanel.tsx
> +  const { sidePanelContent } = useSidePanel();
This is a presentational component, and state mapping should happen within the container (`AppSidePanel`).

2023-09-05 13:49 UTC, petermakowski commented on src/app/base/components/AppSidePanel/AppSidePanel.tsx
> +export const getSidepanelIcon = (sidePanelContent: SidePanelContent | null) => {
If using a tooltip is the way we want to go forward, we should use it across all action forms IMO.

2023-09-05 14:20 UTC, Jay-Topher commented on src/app/base/components/AppSidePanel/AppSidePanel.tsx
> +export const getSidepanelIcon = (sidePanelContent: SidePanelContent | null) => {
The example here looks different from the design spec, would you suggest I use the `buttonsHelp` to display the information instead?

2023-09-05 14:24 UTC, Jay-Topher commented on src/app/base/components/AppSidePanel/AppSidePanel.tsx
> +export const getSidepanelIcon = (sidePanelContent: SidePanelContent | null) => {
Okay, I'll make the necessary changes, thanks

2023-09-06 09:04 UTC, petermakowski requested changes
This looks much better! I have a few suggestions for improvements below.

2023-09-06 09:04 UTC, petermakowski commented on src/app/base/components/node/FieldlessForm/FieldlessForm.tsx
> +          action === NodeActions.SOFT_OFF ? { stop_mode: "soft" } : {};
It would be cleaner if this was moved to soft power off action that you created in `src/app/store/machine/slice.ts`

2023-09-07 11:23 UTC, petermakowski requested changes

2023-09-07 11:23 UTC, petermakowski commented on src/app/base/components/node/FieldlessForm/FieldlessForm.tsx
> +export type FieldlessFormProps<E = null> = NodeActionFormProps<E> & {
This is a good change 👍

2023-09-07 11:23 UTC, petermakowski commented on src/app/store/machine/slice.ts
> +    },
This should be covered by tests. You can add them in `src/app/store/machine/reducers.test.ts`, you could start by adding a new test case with:

`expect(reducers(initialState, actions.softOff())).toEqual(`

2023-09-08 11:43 UTC, petermakowski approved these changes
LGTM

2023-09-08 11:43 UTC, merged