feat(machines): Add "Deployment target" to deploy form MAASENG-2159
canonical/maas-ui pull request #5158
Opened 2023-09-13 14:13 UTC by ndv99

## Done

- Added "Deployment target" section to deploy form
- Added `ephemeral_deploy` to node deployment action parameters
- Hide "Register as MAAS KVM host" if "Deploy in memory" is selected

## QA

### MAAS deployment

To run this branch you will need access to one of the following MAAS deployments:

- [Karura](/HACKING.md#karura)
- [Bolla](/HACKING.md#bolla)
- [A development MAAS](/HACKING.md#development-deployment)
- [A local snap MAAS](/HACKING.md#snap-deployment) (this will not usually have machines)

### Running the branch

You can run this branch by:

- Serving with [dotrun](/HACKING.md#maas-ui-development-setup)
- [Building in a development MAAS](/HACKING.md#running-maas-ui-from-a-development-maas)

### QA steps

**Prerequisite**: Ensure you have dev tools open on the network tab, and inspect the websocket connection

1. Go to machine list
2. Select a machine
3. Open the deploy form
4. Ensure that "Deployment target" is shown
5. Click "Deploy in memory"
6. Ensure that "Register as MAAS KVM host" is hidden
7. Submit the form
8. Ensure a websocket message was sent to deploy the machine, containing `ephemeral_deploy: true`
9. Repeat steps 3-8 for a selection of multiple machines

## Fixes

Fixes [MAASENG-2159](https://warthogs.atlassian.net/browse/MAASENG-2159)

## Screenshots

### Before
![image](https://github.com/canonical/maas-ui/assets/35104482/4a6473fc-2cca-4454-96f0-ba79fd59d16e)

### After
![image](https://github.com/canonical/maas-ui/assets/35104482/eeeb3f8a-3c2d-4389-8f3f-185bb3c12f9f)

![image](https://github.com/canonical/maas-ui/assets/35104482/1aa1d268-1dbf-44b8-88c1-f8710ff39903)

2023-09-13 14:13 UTC, webteam-app commented
Demo starting at https://maas-ui-5158.demos.haus

2023-09-14 07:35 UTC, petermakowski requested changes
`DeployFormFields` component triggers a warning below. Please review and make sure we map and update formik form values correctly.

```
Warning: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
    at input
    at label
    at CheckableInput (http://localhost:8400/MAAS/r/static/js/bundle.js:198401:24)
    at RadioInput (http://localhost:8400/MAAS/r/static/js/bundle.js:206440:20)
    at div
    at div
    at Field (http://localhost:8400/MAAS/r/static/js/bundle.js:201238:23)
    at Input (http://localhost:8400/MAAS/r/static/js/bundle.js:201889:22)
    at div
    at Col (http://localhost:8400/MAAS/r/static/js/bundle.js:199535:23)
    at div
    at Row (http://localhost:8400/MAAS/r/static/js/bundle.js:206563:23)
    at div
    at DeployFormFields
```

2023-09-14 08:30 UTC, Jay-Topher commented
QA works as expected, Only noticed the issue raised by Peter

2023-09-14 13:48 UTC, petermakowski approved these changes

2023-09-14 13:49 UTC, merged