feat: make settings width consistent
canonical/maas-ui pull request #5233
Opened 2023-12-07 15:43 UTC by Jay-Topher

## Done
- Upgraded `@canonical/maas-react-components`
- made settings views with forms half width and aligned action buttons to the right.
- made views with tables to occupy the full width available
- Added titles to all settings pages

## QA steps

- [x] Visit `/settings` and all its sub-routes
- [x] Ensure that all pages under settings have a title same as the side nav link title
- [x] Ensure width of form and tabular views respectively are consistent

## Fixes

Fixes: [MAASENG-2403](https://warthogs.atlassian.net/browse/MAASENG-2403)

## Screenshots
### Before
![image](https://github.com/canonical/maas-ui/assets/47540149/6e9955ea-eef2-41df-ba02-d4fd618bb6ee)

### After
![image](https://github.com/canonical/maas-ui/assets/47540149/60593871-3009-4f15-9c34-3caf7ed6f605)

## Notes

[MAASENG-2403]: https://warthogs.atlassian.net/browse/MAASENG-2403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-12-07 15:43 UTC, webteam-app commented
Demo starting at https://maas-ui-5233.demos.haus

2023-12-07 16:02 UTC, ndv99 reviewed
I think this looks good so far, just a few comments below

2023-12-07 16:02 UTC, ndv99 commented on src/scss/index.scss
> +// @import "./patterns_table-actions";
Remember to remove this!

2023-12-07 16:02 UTC, ndv99 commented on src/scss/index.scss
> +// @include maas-table-actions;
(and this!)

2023-12-07 16:02 UTC, ndv99 commented on src/app/settings/views/Configuration/General/General.tsx
> +    <ContentSection>
Since this page doesn't contain a table, shouldn't this be half width?

2023-12-07 16:02 UTC, ndv99 commented on src/app/settings/views/Security/SecretStorage/SecretStorage.tsx
> +    <ContentSection>
Shouldn't this be half width too?

2023-12-08 15:19 UTC, ndv99 requested changes
`/settings/configuration/general` needs some changes IMO - there's definitely not enough space for the theme colour labels in this layout. I'd suggest modifying this so that the default layout for these is two rows of five.

![image](https://github.com/canonical/maas-ui/assets/35104482/272dac9b-d8ff-4b4a-968d-fa76fe71e29f)

2023-12-11 09:15 UTC, petermakowski commented
![Google Chrome screenshot 001200@2x](https://github.com/canonical/maas-ui/assets/7452681/157bede6-5da3-4d53-80da-4d04a81f49fc)

@Jay-Topher Headings should be aligned. Please remove the `<section class="p-strip is-shallow">` wrapper that's responsible for the additional padding. In case there are still some minor discrepancies, I'll resolve them in `maas-react-components`.

2023-12-11 17:01 UTC, ndv99 approved these changes
I'm happy with this personally, everything looks good to me. Nice one mate!

2023-12-12 07:37 UTC, petermakowski commented
LGTM

2023-12-12 07:37 UTC, petermakowski approved these changes

2023-12-12 07:38 UTC, petermakowski commented
@Jay-Topher Changed prefix to `feat:` as this affects the end user.

2023-12-12 07:44 UTC, merged